### PR TITLE
Issue1 fix

### LINKED ISSUE #1: concantjson explodes with strings including a {
concantjson "explodes" i.e. generates an uncaught parser error, when trying to parse `{}{"foo":"{"}`. Somehow concantjson doesn't handle curly brackets right. And yes, they don't need to be escaped according to RFC 7159, and the subjson `{"foo":"{"}` is parsed without problems by JSON.parse()

### PR DESCRIPTION
**Pull request by Superlokkus**
Test and fixes #1

### CODE REVIEW

**Comment by manidlou** [comment]
@Superlokkus thanks for your contribution. Will you squash this please?

**Comment by Superlokkus** [comment]
@manidlou I would like to, but as far as I understand https://github.com/blog/2141-squash-your-commits only you (or any maintainer) can summerize/squash my commits via this merge request. (Cant find the button anywhere) ("To squash and merge pull requests, you must have write permissions in the repository, and the repository must allow squash merging.")

**Comment by manidlou** [comment]
You can do it via your branch (interactive rebase). If you haven't take a look at this before, I invite you to read https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request, specifically the part about `Squash your changes`.

**Comment by Superlokkus** [comment]
Done

**Comment by manidlou** [comment]
Thanks @Superlokkus!

**Comment by manidlou** [comment]
`v2.0.0` is released!

**Pull request merged**
